#!/bin/bash

# setup environment variables
export HyperQuantCrowdsaleRate=1
export HyperQuantCrowdsaleFundAddress=0xffffffffffffffffffffffffffffffffffffffff
export HyperQuantCrowdsaleTokensCap=1
export NetworksRinkebyFrom=0xffffffffffffffffffffffffffffffffffffffff
export NetworksPrivateFrom=0xffffffffffffffffffffffffffffffffffffffff
